# Generated by Django 2.1.7 on 2019-04-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharetext', '0002_auto_20190413_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
